//
// Created by nazirov on 23.10.2021.
//

#ifndef LAB4_LIMITATION_H
#define LAB4_LIMITATION_H
#define MAX_SIZE_OF_STACK 10000
#define MAX_RANDOM_VALUE 100
#define MAX_RANDOM_ZNAK_VALUE 2
#endif //LAB4_LIMITATION_H
